name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - '**' # This triggers on all branches

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          BASE_PATH: ${{ github.ref == 'refs/heads/master' && format('/{0}', github.event.repository.name) || format('/{0}/staging/{1}', github.event.repository.name, env.BRANCH_NAME) }}
        run: |
          pnpm run build

      # Upload different artifacts based on branch
      - name: Upload Production Artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

      - name: Upload Staging Artifacts
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: staging-build
          path: build/
          retention-days: 1

  deploy-production:
    if: github.ref == 'refs/heads/master'
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-staging:
    if: github.ref != 'refs/heads/master'
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - name: Download staging artifacts
        uses: actions/download-artifact@v3
        with:
          name: staging-build
          path: build

      - name: Deploy to staging
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          target-folder: staging/${{ env.BRANCH_NAME }}
